apiVersion: v1
kind: Pod
metadata:
  name: alma
  namespace: default
  labels:
    name: roboshop
    environment: Dev
  annotations:
    Imagedir: https://imagesdocker.co.in
spec:
  containers:
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
  - name: nginx
    image: nginx