apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: default
  labels:
    name: roboshop
    environment: Dev
    component: frontend
spec:
  containers:
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
  - name: nginx
    image: nginx