apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as selectors
    name: roboshop
    environment: Dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port
